/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_juanjo_openDmx_OpenDmx */

#ifndef _Included_com_juanjo_openDmx_OpenDmx
#define _Included_com_juanjo_openDmx_OpenDmx
#ifdef __cplusplus
extern "C" {
#endif
#undef com_juanjo_openDmx_OpenDmx_OPENDMX_TX
#define com_juanjo_openDmx_OpenDmx_OPENDMX_TX 0L
#undef com_juanjo_openDmx_OpenDmx_OPENDMX_RX
#define com_juanjo_openDmx_OpenDmx_OPENDMX_RX 1L
/*
 * Class:     com_juanjo_openDmx_OpenDmx
 * Method:    getList
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_juanjo_openDmx_OpenDmx_getList
  (JNIEnv *, jclass);

/*
 * Class:     com_juanjo_openDmx_OpenDmx
 * Method:    connect
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_juanjo_openDmx_OpenDmx_connect
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_juanjo_openDmx_OpenDmx
 * Method:    disconnect
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_juanjo_openDmx_OpenDmx_disconnect
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_juanjo_openDmx_OpenDmx
 * Method:    setValue
 * Signature: (II)V
 */
JNIEXPORT jint JNICALL Java_com_juanjo_openDmx_OpenDmx_setValue
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_juanjo_openDmx_OpenDmx
 * Method:    getValue
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_juanjo_openDmx_OpenDmx_getValue
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
