/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.robotarmy.dmx;

import org.openide.util.NbBundle;
import org.openide.util.NbPreferences;

@NbBundle.Messages({
    "PREF_LastPortUsed0=lastPortUsed0",
    "PREF_LastPortUsed1=lastPortUsed1",
    "PREF_AutoConnect=autoConnect"
})
final class SerialPortSettingsPanel extends javax.swing.JPanel {

    private final SerialPortSettingsOptionsPanelController controller;

    SerialPortSettingsPanel(SerialPortSettingsOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lastUsedSerialLabel0 = new javax.swing.JLabel();
        lastUsedSerialValue0 = new javax.swing.JLabel();
        autoConnectCheckBox = new javax.swing.JCheckBox();
        lastUsedSerialLabel1 = new javax.swing.JLabel();
        lastUsedSerialValue1 = new javax.swing.JLabel();

        lastUsedSerialLabel0.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(lastUsedSerialLabel0, org.openide.util.NbBundle.getMessage(SerialPortSettingsPanel.class, "SerialPortSettingsPanel.lastUsedSerialLabel0.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lastUsedSerialValue0, org.openide.util.NbBundle.getMessage(SerialPortSettingsPanel.class, "SerialPortSettingsPanel.lastUsedSerialValue0.text")); // NOI18N

        autoConnectCheckBox.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(autoConnectCheckBox, org.openide.util.NbBundle.getMessage(SerialPortSettingsPanel.class, "SerialPortSettingsPanel.autoConnectCheckBox.text")); // NOI18N

        lastUsedSerialLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(lastUsedSerialLabel1, org.openide.util.NbBundle.getMessage(SerialPortSettingsPanel.class, "SerialPortSettingsPanel.lastUsedSerialLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lastUsedSerialValue1, org.openide.util.NbBundle.getMessage(SerialPortSettingsPanel.class, "SerialPortSettingsPanel.lastUsedSerialValue1.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lastUsedSerialLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastUsedSerialValue1))
                    .addComponent(autoConnectCheckBox)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lastUsedSerialLabel0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastUsedSerialValue0)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lastUsedSerialValue0)
                    .addComponent(lastUsedSerialLabel0, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lastUsedSerialValue1)
                    .addComponent(lastUsedSerialLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(autoConnectCheckBox)
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    void load() {
        lastUsedSerialValue0.setText(
                NbPreferences.forModule(SerialPortSettingsPanel.class).get(
                        Bundle.PREF_LastPortUsed0(), "none"
        ));
        lastUsedSerialValue1.setText(
                NbPreferences.forModule(SerialPortSettingsPanel.class).get(
                        Bundle.PREF_LastPortUsed1(), "none"
        ));
        
        autoConnectCheckBox.setSelected(NbPreferences.forModule(SerialPortSettingsPanel.class).getBoolean(Bundle.PREF_AutoConnect(), true));
        // TODO read settings and initialize GUI
        // Example:        
        // someCheckBox.setSelected(Preferences.userNodeForPackage(SerialPortSettingsPanel.class).getBoolean("someFlag", false));
        // or for org.openide.util with API spec. version >= 7.4:
        // someCheckBox.setSelected(NbPreferences.forModule(SerialPortSettingsPanel.class).getBoolean("someFlag", false));
        // or:
        // someTextField.setText(SomeSystemOption.getDefault().getSomeStringProperty());
    }

    void store() {
        NbPreferences.forModule(SerialPortSettingsPanel.class).put(Bundle.PREF_LastPortUsed0(), lastUsedSerialValue0.getText());
        NbPreferences.forModule(SerialPortSettingsPanel.class).put(Bundle.PREF_LastPortUsed1(), lastUsedSerialValue1.getText());
        NbPreferences.forModule(SerialPortSettingsPanel.class).putBoolean(Bundle.PREF_AutoConnect(), autoConnectCheckBox.isSelected());
        // TODO store modified settings
        // Example:
        // Preferences.userNodeForPackage(SerialPortSettingsPanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        // or for org.openide.util with API spec. version >= 7.4:
        // NbPreferences.forModule(SerialPortSettingsPanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        // or:
        // SomeSystemOption.getDefault().setSomeStringProperty(someTextField.getText());
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox autoConnectCheckBox;
    private javax.swing.JLabel lastUsedSerialLabel0;
    private javax.swing.JLabel lastUsedSerialLabel1;
    private javax.swing.JLabel lastUsedSerialValue0;
    private javax.swing.JLabel lastUsedSerialValue1;
    // End of variables declaration//GEN-END:variables
}
