/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.robotarmy.dmx;

import org.openide.util.NbBundle;
import org.openide.util.NbPreferences;

@NbBundle.Messages({
    "PREF_LastPortUsed=lastPortUsed"
})
final class SerialPortSettingsPanel extends javax.swing.JPanel {

    private final SerialPortSettingsOptionsPanelController controller;

    SerialPortSettingsPanel(SerialPortSettingsOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lastUsedSerialLabel = new javax.swing.JLabel();
        lastUsedSerialValue = new javax.swing.JLabel();

        lastUsedSerialLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(lastUsedSerialLabel, org.openide.util.NbBundle.getMessage(SerialPortSettingsPanel.class, "SerialPortSettingsPanel.lastUsedSerialLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lastUsedSerialValue, org.openide.util.NbBundle.getMessage(SerialPortSettingsPanel.class, "SerialPortSettingsPanel.lastUsedSerialValue.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lastUsedSerialLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastUsedSerialValue)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastUsedSerialLabel)
                    .addComponent(lastUsedSerialValue))
                .addContainerGap(119, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    void load() {
        lastUsedSerialValue.setText(
                NbPreferences.forModule(SerialPortSettingsPanel.class).get(
                        Bundle.PREF_LastPortUsed(), "none"
        ));
        

        // TODO read settings and initialize GUI
        // Example:        
        // someCheckBox.setSelected(Preferences.userNodeForPackage(SerialPortSettingsPanel.class).getBoolean("someFlag", false));
        // or for org.openide.util with API spec. version >= 7.4:
        // someCheckBox.setSelected(NbPreferences.forModule(SerialPortSettingsPanel.class).getBoolean("someFlag", false));
        // or:
        // someTextField.setText(SomeSystemOption.getDefault().getSomeStringProperty());
    }

    void store() {
        NbPreferences.forModule(SerialPortSettingsPanel.class).put(Bundle.PREF_LastPortUsed(), lastUsedSerialValue.getText());

        // TODO store modified settings
        // Example:
        // Preferences.userNodeForPackage(SerialPortSettingsPanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        // or for org.openide.util with API spec. version >= 7.4:
        // NbPreferences.forModule(SerialPortSettingsPanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        // or:
        // SomeSystemOption.getDefault().setSomeStringProperty(someTextField.getText());
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lastUsedSerialLabel;
    private javax.swing.JLabel lastUsedSerialValue;
    // End of variables declaration//GEN-END:variables
}
