/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.robotarmy.leapmotion;

import com.leapmotion.leap.Controller;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author mark
 */
public class LeapConnectionIndicatorPanel extends javax.swing.JPanel implements ActionListener  {
    private Timer timer;
    private final Controller controller = new Controller();
    private boolean leapConnected = false;

    /**
     * Creates new form LeapConnectionIndicatorPanel
     */
    public LeapConnectionIndicatorPanel() {
        initComponents();
        
        timer = new Timer(1000, this);
        timer.setInitialDelay(1000);
        timer.start();
    }
    
    // Called by Timer at about 30FPS
    @Override
    public void actionPerformed(ActionEvent ae) {
        if (controller.isConnected()) {
            if (!leapConnected) {
                leapConnected = true;
                statusPanel.setBackground(Color.GREEN);
            }
        } else {
            leapConnected = false;
            statusPanel.setBackground(Color.RED);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusPanel = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        setPreferredSize(new java.awt.Dimension(90, 24));

        statusPanel.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.select"));
        statusPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 4, true));
        statusPanel.setPreferredSize(new java.awt.Dimension(100, 20));

        statusLabel.setFont(new java.awt.Font("Myriad Pro", 1, 12)); // NOI18N
        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(statusLabel, org.openide.util.NbBundle.getMessage(LeapConnectionIndicatorPanel.class, "LeapConnectionIndicatorPanel.statusLabel.text")); // NOI18N
        statusLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 3, 1, 3));
        statusLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        statusLabel.setMaximumSize(new java.awt.Dimension(33, 18));
        statusLabel.setMinimumSize(new java.awt.Dimension(33, 18));
        statusLabel.setPreferredSize(new java.awt.Dimension(33, 18));

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(statusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel statusLabel;
    private javax.swing.JPanel statusPanel;
    // End of variables declaration//GEN-END:variables
}
