/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.robotarmy.leap.ui;

import javax.swing.border.TitledBorder;

/**
 *
 * @author mark
 */
public class HandPanel extends javax.swing.JPanel {

    public static final boolean DIR_LEFT = false;
    public static final boolean DIR_RIGHT = true;
    
    /**
     * Creates new form handPanel
     */
    public HandPanel() {
        initComponents();
    }

    public void setLabel( String text ) {
        ((TitledBorder)borderPanel.getBorder()).setTitle(text);
    }
    
    public void update(int x, int y, int z) {
        xValue.setText(String.valueOf(x));
        yValue.setText(String.valueOf(y));
        zValue.setText(String.valueOf(z));
        xYPanel.setXY(x,y);
        zPanel.setValue(z);
        repaint();
    }
    
    public void updateFingers(int[] fingZ, boolean dir) {
        if ( dir == DIR_RIGHT ) {
            fingerPanel1.setValue(fingZ[0]);
            fingerPanel2.setValue(fingZ[1]);
            fingerPanel3.setValue(fingZ[2]);
            fingerPanel4.setValue(fingZ[3]);
            fingerPanel5.setValue(fingZ[4]);
        } else {
            fingerPanel1.setValue(fingZ[4]);
            fingerPanel2.setValue(fingZ[3]);
            fingerPanel3.setValue(fingZ[2]);
            fingerPanel4.setValue(fingZ[1]);
            fingerPanel5.setValue(fingZ[0]);            
        }
        repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        borderPanel = new com.robotarmy.leap.ui.BorderPanel();
        xLabel = new javax.swing.JLabel();
        xValue = new javax.swing.JLabel();
        yLabel = new javax.swing.JLabel();
        yValue = new javax.swing.JLabel();
        zValue = new javax.swing.JLabel();
        zLabel = new javax.swing.JLabel();
        zPanel = new com.robotarmy.leap.ui.ZPanel();
        fingerPanel2 = new com.robotarmy.leap.ui.FingerPanel();
        fingerPanel3 = new com.robotarmy.leap.ui.FingerPanel();
        fingerPanel4 = new com.robotarmy.leap.ui.FingerPanel();
        fingerPanel5 = new com.robotarmy.leap.ui.FingerPanel();
        xYPanel = new com.robotarmy.leap.ui.XYPanel();
        fingerPanel1 = new com.robotarmy.leap.ui.FingerPanel();

        setPreferredSize(new java.awt.Dimension(160, 300));

        borderPanel.setPreferredSize(new java.awt.Dimension(160, 302));

        org.openide.awt.Mnemonics.setLocalizedText(xLabel, org.openide.util.NbBundle.getMessage(HandPanel.class, "HandPanel.xLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(xValue, org.openide.util.NbBundle.getMessage(HandPanel.class, "HandPanel.xValue.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(yLabel, org.openide.util.NbBundle.getMessage(HandPanel.class, "HandPanel.yLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(yValue, org.openide.util.NbBundle.getMessage(HandPanel.class, "HandPanel.yValue.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(zValue, org.openide.util.NbBundle.getMessage(HandPanel.class, "HandPanel.zValue.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(zLabel, org.openide.util.NbBundle.getMessage(HandPanel.class, "HandPanel.zLabel.text")); // NOI18N

        javax.swing.GroupLayout zPanelLayout = new javax.swing.GroupLayout(zPanel);
        zPanel.setLayout(zPanelLayout);
        zPanelLayout.setHorizontalGroup(
            zPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
        zPanelLayout.setVerticalGroup(
            zPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout fingerPanel2Layout = new javax.swing.GroupLayout(fingerPanel2);
        fingerPanel2.setLayout(fingerPanel2Layout);
        fingerPanel2Layout.setHorizontalGroup(
            fingerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        fingerPanel2Layout.setVerticalGroup(
            fingerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout fingerPanel3Layout = new javax.swing.GroupLayout(fingerPanel3);
        fingerPanel3.setLayout(fingerPanel3Layout);
        fingerPanel3Layout.setHorizontalGroup(
            fingerPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        fingerPanel3Layout.setVerticalGroup(
            fingerPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout fingerPanel4Layout = new javax.swing.GroupLayout(fingerPanel4);
        fingerPanel4.setLayout(fingerPanel4Layout);
        fingerPanel4Layout.setHorizontalGroup(
            fingerPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        fingerPanel4Layout.setVerticalGroup(
            fingerPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout fingerPanel5Layout = new javax.swing.GroupLayout(fingerPanel5);
        fingerPanel5.setLayout(fingerPanel5Layout);
        fingerPanel5Layout.setHorizontalGroup(
            fingerPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        fingerPanel5Layout.setVerticalGroup(
            fingerPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout xYPanelLayout = new javax.swing.GroupLayout(xYPanel);
        xYPanel.setLayout(xYPanelLayout);
        xYPanelLayout.setHorizontalGroup(
            xYPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );
        xYPanelLayout.setVerticalGroup(
            xYPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout fingerPanel1Layout = new javax.swing.GroupLayout(fingerPanel1);
        fingerPanel1.setLayout(fingerPanel1Layout);
        fingerPanel1Layout.setHorizontalGroup(
            fingerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        fingerPanel1Layout.setVerticalGroup(
            fingerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout borderPanelLayout = new javax.swing.GroupLayout(borderPanel);
        borderPanel.setLayout(borderPanelLayout);
        borderPanelLayout.setHorizontalGroup(
            borderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borderPanelLayout.createSequentialGroup()
                .addGroup(borderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(borderPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(borderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(borderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(borderPanelLayout.createSequentialGroup()
                                .addComponent(fingerPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fingerPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fingerPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fingerPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fingerPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(xValue)
                            .addComponent(yValue)
                            .addComponent(zValue))
                        .addGap(18, 18, 18)
                        .addComponent(zPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(borderPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(xYPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        borderPanelLayout.setVerticalGroup(
            borderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(borderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(borderPanelLayout.createSequentialGroup()
                        .addGroup(borderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(xLabel)
                            .addComponent(xValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(borderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yLabel)
                            .addComponent(yValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(borderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zLabel)
                            .addComponent(zValue)))
                    .addGroup(borderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(borderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(borderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fingerPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fingerPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fingerPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fingerPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fingerPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(zPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xYPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(borderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(borderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.robotarmy.leap.ui.BorderPanel borderPanel;
    private com.robotarmy.leap.ui.FingerPanel fingerPanel1;
    private com.robotarmy.leap.ui.FingerPanel fingerPanel2;
    private com.robotarmy.leap.ui.FingerPanel fingerPanel3;
    private com.robotarmy.leap.ui.FingerPanel fingerPanel4;
    private com.robotarmy.leap.ui.FingerPanel fingerPanel5;
    private javax.swing.JLabel xLabel;
    private javax.swing.JLabel xValue;
    private com.robotarmy.leap.ui.XYPanel xYPanel;
    private javax.swing.JLabel yLabel;
    private javax.swing.JLabel yValue;
    private javax.swing.JLabel zLabel;
    private com.robotarmy.leap.ui.ZPanel zPanel;
    private javax.swing.JLabel zValue;
    // End of variables declaration//GEN-END:variables

}
