/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.robotarmy.leap.ui;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author mark
 */
public class XYPanel extends javax.swing.JPanel {

    private int x = 127;
    private int y = 127;
    private int dotSize = 4;
    
    /**
     * Creates new form XYPanel
     */
    public XYPanel() {
        initComponents();
    }

    /**
     * 
     * @param x a value between 0 - 255
     * @param y a value between 0 - 255
     */
    public void setXY( int x, int y) {
        this.x = x;
        this.y = y;
        repaint();
    }

    @Override
    public void paint(Graphics grphcs) {
        super.paint(grphcs); //To change body of generated methods, choose Tools | Templates.
        grphcs.setColor(Color.yellow);
        grphcs.fillOval(x/2-dotSize/2, y/2-dotSize/2, dotSize, dotSize);
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(102, 102, 102));
        setPreferredSize(new java.awt.Dimension(128, 128));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
